config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stores do
    collection do
      get 'add'
      post 'add_create'
      get 'search'
    end
  end

  scope path: 'user' do
    resources :stores, controller: 'user_stores', as: 'user_stores' do
      # post 'archive', on: :member
      # post 'unarchive', on: :member

      collection do
        get 'add'
        post 'add'
      end
    end
  end
  post 'user/stores/link', to: 'user_stores#link', as: :link_user_store

  # Define routes for the Api::ZipCodesController
  namespace :api, defaults: { format: 'json' } do
    get 'zip_codes/zip_code_data/:zip_code', to: 'zip_codes#zip_code_data', as: :zip_code_data
  end

  resources :items, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  resources :shopping_lists

  scope path: 'user' do
    resources :shopping_lists, controller: 'user_shopping_lists', as: :user_shopping_lists do
      collection do
        get 'add'
        post 'add'
      end
    end
  end

  resources :labels, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  devise_for :users
end

app/models/store.rb
# frozen_string_literal: true

# The store model for this application.
class Store < ApplicationRecord
  include ArchivableConcern

  before_save :before_save_edits

  attr_reader :non_unique_store_id

  scope :where_name_and_zip_case_insensitive, lambda { |store_name, zip_code|
    where('LOWER(store_name) = LOWER(?) AND zip_code = ?', store_name, zip_code)
  }

  belongs_to :state

  has_many :user_stores
  has_many :users, through: :user_stores, source: :user

  validates :store_name, :address, :city, presence: true, length: { maximum: 64 }
  validates :address2, length: { maximum: 64 }, allow_blank: true

  # Validates :zip_code which could be 5 digits with optional 4 digit extension.
  validates :zip_code, format: { with: /\A\d{5}(-\d{4})?\z/ }

  validate :store_name_within_zip_code_unique, if: -> { store_name_and_zip_code? }

  def non_unique_store?
    !unique_store?
  end

  def unique_store?
    return true unless store_name_and_zip_code?

    store = self.class.where_name_and_zip_case_insensitive(store_name, zip_code).first
    return true unless store

    # This attribute (id) will be populated with the id of the
    # store that already exists with the same name and zip code.
    self.non_unique_store_id = store.id unless store.id == id

    non_unique_store_id.nil?
  end

  private

  attr_writer :non_unique_store_id

  def store_name_within_zip_code_unique
    return true if unique_store?

    errors.add(:base, I18n.t('activerecord.errors.models.store.already_exists'))
  end

  def store_name_and_zip_code?
    store_name.present? && zip_code.present?
  end

  def before_save_edits
    store_name[0] = store_name[0].upcase if store_name.present?
    self.address = address.titleize
    self.address2 = address2.titleize if address2.present?
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

# The store controller for this application.
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_store, only: %i[show edit update destroy]

  # GET /stores or /stores.json
  def index
    @resource = current_user.stores.order(:store_name).presenter(current_user)
  end

  # GET /stores/1 or /stores/1.json
  def show; end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit; end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /stores/add
  def add
    @resource = all_stores
  end

  # POST /stores/add_create
  def add_create
    success = UserStore.new(user_id: current_user.id, store_id: add_create_params[:store_id]).save
    @resource = all_stores
    if success
      redirect_to add_create_stores_path, notice: 'Store was successfully added.'
    else
      # You might want to handle the error differently, perhaps redirecting back with a flash message.
      redirect_to add_create_stores_path, alert: 'There was an error adding the store.'
    end
  end

  # GET /stores/search
  def search; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  def all_stores
    Store.all.order(:store_name).presenter(current_user)
  end

  # Only allow a list of trusted parameters through.
  def store_params
    params.require(:store).permit(:store_name, :address, :address2, :city, :state_id, :zip_code)
  end

  def add_create_params
    params.require(:store).permit(:store_id)
  end
end

app/views/stores/_form.html.erb
<div data-controller="zip-code">
  <main class="devise-form form-store-new">
    <%= simple_form_for(store, wrapper: :horizontal_form) do |f| %>
      <div class="h1 mb-3 fw-normal"><%= header_text %></div>

      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :store_name,
                  label: "Name",
                  autofocus: true
      %>
      <%= f.input :address,
                  label: "Address"
      %>
      <%= f.input :address2,
                  label: "Address 2"
      %>
      <%= f.input :zip_code,
                  required: true,
                  input_html: {
                    data: {
                      "zip-code-target": "zipCode",
                      action: "blur->zip-code#fetchCityAndStateFromZipCode"
                    }
                  }
      %>
      <%= f.input :city,
                  input_html: {
                    data: {
                      "zip-code-target": "city"
                    }
                  }
      %>
      <%= f.association :state,
                        wrapper: :horizontal_form,
                        label_method: lambda { |state|
                          "#{state.state_name} (#{state.postal_abbreviation})"
                        },
                        prompt: "Select a state",
                        input_html: {
                          data: {
                            "zip-code-target": "state"
                          }
                        }
      %>

      <div class="form-actions">
        <%= f.button :submit,
                     class: "btn btn-primary",
                     data: {
                      "zip-code-target": "submitButton"
                     }
        %>
      </div>
    <% end %>

    <div class="help-links">
      <%= link_to "Back", back_path %>
    </div>
  </main>
</div>

app/views/stores/_store.html.erb
<tr id="<%= dom_id store %>" >
  <th scope="row"><%= store_counter + 1 %></th>
  <td><%= store.store_name %></th>
  <td><%= store.address_with_address2 %></th>
  <td><%= store.city %></th>
  <td><%= store.state.postal_abbreviation %></th>
  <td><%= store.zip_code %></th>
  <td>
    <% if store.user_store? %>
      <span class="badge text-bg-success">
        <i class="bi bi-check-circle-fill"></i>
        Already added
      </span>
    <% elsif mode == :add %>
      <%= simple_form_for :store, url: add_create_stores_path, method: :post do |f| %>
        <%= f.input :store_id, as: :hidden, input_html: { value: store.id } %>
        <button type="submit" class="btn btn-outline-primary btn-sm">
          <i class="bi bi-building-fill-add"></i> Add
        </button>
      <% end %>
    <% else %>
      <%= link_to store_path(store), class: "btn btn-outline-primary btn-sm" do %>
        <i class="bi bi-eye-fill"></i> View
      <% end %>
    <% end %>
  </td>
</tr>

app/views/stores/_stores.html.erb
<table id="stores" class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Zip code</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <thead data-target="filter" class="d-none">
    <tr>
      <th scope="col">&nbsp;</th>
      <th data-type="store_name" scope="col">
        <!-- name search input box -->
      </th>
      <th data-type="street" scope="col">
        <!-- street search input box -->
      </th>
      <th data-type="city" scope="col">
        <!-- city search input box -->
      </th>
      <th data-type="state" scope="col">
        <!-- state search input box -->
      </th>
      <th data-type="zip-code" scope="col">
        <!-- zip_code search input box -->
      </th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>
  <tbody data-target="filter">
    <%= render partial: 'stores/store', collection: stores, locals: { mode: mode } %>
  </tbody>
</table>

app/views/stores/add.html.erb
<main class="form form-list-stores m-auto">
  <div data-controller="filter">
    <div class="h1 mb-3 fw-normal"><i class="bi bi-building-check"></i>Add a Store</div>
    <%= render partial: "stores", locals: { stores: @resource, mode: :add } %>
  </div>
  <% unless @resource.stores.any? %>
  <div>
    The <%= render partial: "shared/site_name", locals: { mode: :dark } %>
    universe currently has no stores! Save the world and add some!
  </div>
  <% end %>
</main>

<div class="help-links">
  <%= link_to new_store_path, class: "btn btn-primary" do %>
    <i class="bi bi-building-add"></i>New store
  <% end %>
</div>

app/views/stores/index.html.erb
<%
add_a_store_button_text = "Add a store"
%>
<main class="form form-list-stores m-auto">
  <div data-controller="filter">
    <div class="h1 mb-3 fw-normal"><i class="bi bi-building"></i> My Stores</div>
    <%= render partial: "stores", locals: { stores: @resource, mode: :list } %>
  </div>
  <% unless @resource.stores.any? %>
  <div>
    You currently have no stores.
    You can add one by clicking the
    <strong>
      <i class="bi bi-building-check"></i> <%= add_a_store_button_text %>
    </strong>
    button below.
  </div>
  <% end %>
</main>

<div class="help-links">
  <%= link_to add_stores_path, class: "btn btn-primary" do %>
    <i class="bi bi-building-check"></i> <%= add_a_store_button_text %>
  <% end %>
</div>

app/views/stores/new.html.erb
<%= render "form", store: @store, states: @states, header_text: "New Store", back_path: stores_path %>