config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stores do
    collection do
      get 'add'
      post 'add_create'
      get 'search'
    end
  end

  scope path: 'user' do
    resources :stores, controller: 'user_stores', as: 'user_stores' do
      # post 'archive', on: :member
      # post 'unarchive', on: :member

      collection do
        get 'add'
        post 'add'
      end
    end
  end
  post 'user/stores/link', to: 'user_stores#link', as: :link_user_store

  # Define routes for the Api::ZipCodesController
  namespace :api, defaults: { format: 'json' } do
    get 'zip_codes/zip_code_data/:zip_code', to: 'zip_codes#zip_code_data', as: :zip_code_data
  end

  resources :items, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  resources :shopping_lists

  scope path: 'user' do
    resources :shopping_lists, controller: 'user_shopping_lists', as: :user_shopping_lists do
      collection do
        get 'add'
        post 'add'
      end
    end
  end

  resources :labels, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  devise_for :users
end

app/models/label.rb
# frozen_string_literal: true

# The Label model for this application.
class Label < ApplicationRecord
  include ArchivableConcern
  include PagableConcern

  has_many :item_labels, dependent: :destroy
  has_many :items, through: :item_labels

  accepts_nested_attributes_for :item_labels

  validates :label_name, presence: true, uniqueness: { case_sensitive: false }

  attr_accessor :query

  def to_hash
    {
      id: id,
      label_name: label_name,
      items: sorted_items
    }
  end

  def to_json(*args)
    to_hash.to_json(*args)
  end

  private

  # TODO: Put this in a mixin.
  def sorted_items
    items.order(item_name: :asc).map do |item|
      {
        id: item.id,
        item_name: item.item_name,
        archived: item.archived
      }
    end
  end
end

app/controllers/labels_controller.rb
# frozen_string_literal: true

# The controller for item labels.
class LabelsController < ApplicationController
  include ItemSearchConcern

  before_action :authenticate_user!
  before_action :set_label, only: %i[edit update archive unarchive]

  # GET /labels or /labels.json
  def index
    page = params[:page].to_i
    pager_params = Label.pager_params_for(page: page,
                                          pages_between: pager_pages_between,
                                          items_per_page: pager_items_per_page,
                                          pager_path: labels_path)
    @pager_params = PagerPresenter.new(pager_params: pager_params, user: current_user, view_context: view_context)
    labels = Label.page_for(page: page,
                            order_by: [label_name: :ASC],
                            items_per_page: pager_items_per_page)
    @labels = PresenterDecorator.new(resource: labels,
                                     user: current_user,
                                     view_context: view_context)
  end

  # GET /labels/1 or /labels/1.json
  def show
    label = Label.find(params[:id])
    @label = PresenterDecorator.new(resource: label, user: current_user, view_context: view_context)
  end

  # GET /labels/new
  def new
    label = Label.new
    @label = PresenterDecorator.new(resource: label, user: current_user, view_context: view_context)
    render layout: 'label'
  end

  # GET /labels/1/edit
  def edit
    render layout: 'label'
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_url, notice: 'Label was successfully created.'
    else
      @label = PresenterDecorator.new(resource: @label, user: current_user, view_context: view_context)
      render :new, status: :unprocessable_entity, layout: 'label'
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    Rails.logger.info("xyzzy: params: #{params.inspect}")
    Rails.logger.info("xyzzy: label_params: #{label_params.inspect}")

    ActiveRecord::Base.transaction do
      @label.item_labels.clear
      if @label.update(label_params)
        redirect_to labels_url, notice: 'Label was successfully updated.'
      else
        render :edit, status: :unprocessable_entity, layout: 'label'
        raise ActiveRecord::Rollback
      end
    end
  rescue StandardError => e
    Rails.logger.error("xyzzy: class: #{e.class}, error: #{e.message}")

    flash[:alert] = 'An error occurred and the label could not be updated. No more information is available.'
    render :edit, status: :unprocessable_entity, layout: 'label'
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    label = Label.find_by(id: params[:id])
    if label
      label.destroy
      redirect_to labels_url, notice: 'Label was successfully destroyed.'
    else
      redirect_to labels_url,
                  status: :not_found,
                  alert: 'The label could not not found.'
    end
  end

  # GET /labels/search
  def search
    locals = {
      search_results: @search_results,
      javascript_controller: 'label-items'
    }
    render partial: 'shared/item_search_results', locals: locals, layout: false
  end

  # POST /labels/1 or /labels/1.json
  def archive
    @label.archive!

    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully archived.' }
      format.json { head :no_content }
    end
  end

  # POST /labels/1 or /labels/1.json
  def unarchive
    @label.unarchive!

    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully unarchived.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_label
    label = Label.find(params[:id])
    @label = PresenterDecorator.new(resource: label, user: current_user, view_context: view_context)
  end

  def label_params
    params[:label]&.delete(:query)
    params[:label]&.delete(:item_ids)
    params.require(:label).permit(
      :label_name,
      :archived,
      item_labels_attributes: [:item_id]
    )
  end
end

app/views/labels/_form.html.erb
<%
method ||= :post
label_presenter = label.presenter
%>
<main class="form form-label">
  <%= simple_form_for(label,
                      url: postback_path,
                      method: method,
                      wrapper: :horizontal_form) do |f| %>
    <div class="h1 mb-3 fw-normal">
      <i class="bi <%= header_icon %>"></i>
      <%= header_text %>
    </div>

    <% if f.object.errors[:base].present? %>
      <div class="row mb-3">
        <div class="col-sm-12 col-md-9 col-lg-7">
          <%= render partial: "shared/flash_message",
                      locals: {
                        flash_type: "alert",
                        flash_message: f.object.errors[:base].to_sentence
                      }
          %>
        </div>
      </div>
    <% end %>
    <%= f.input :label_name,
            required: true,
            label: "Name",
            autofocus: true
    %>
    <div class="form-group row">
      <%= f.label :archived, class: 'col-sm-2 col-md-2 col-lg-2 col-form-label' %>
      <div class="col-sm-9">
        <%= f.input :archived, as: :boolean, label: false, wrapper: false, class: 'form-check-input' %>
      </div>
    </div>

    <!-- Type ahead search -->
    <%= f.input :query,
                label: "Items <abbr title='required'>*</abbr>".html_safe,
                label_html: { class: "required" },
                placeholder: "Search for items to associate with this label",
                autocomplete: "off",
                input_html: {
                  data: {
                    action: "input->label-items#labelItemsSearch",
                    label_items_target: "input"
                  }
                }
    %>

    <div class="row mb-3">
      <div class="col-sm-2 col-md-2 col-lg-2 col-form-label">
          <%= f.button :submit,
                        submit_button_text,
                        class: "btn btn-primary"
          %>
          <div class="help-links">
            <%= link_to "Back", back_path %>
          </div>
      </div>
      <div data-label-items-target="results" class="col-sm-10 col-md-7 col-lg-5">
      </div>
    </div>
    <div data-label-items-target="selectedItemIdsContainer" class="d-none">
    </div>
  <% end %>
</main>

app/views/labels/_label.html.erb
<%#= content_tag(:div, "_label.html.erb: label.class: #{label.class.name}, inspect: #{label.inspect}") %>
<tr id="<%= dom_id label %>" >
  <th scope="row"><%= pager_params.page_offset + label_counter + 1 %></th>
  <td><%= label.display_name %></td>
  <td class="text-center"><%= label.display_archived %></td>
  <td>
    <div class="fixed-width-buttons d-flex justify-content-center">
      <%= form_tag edit_label_path(label), method: :get do |f| %>
        <%= button_tag(type: :submit, class: "btn btn-outline-primary btn-sm ms-1") do %>
          <i class="bi bi-bookmark"></i> Edit
        <% end %>
      <% end %>
      <%= form_tag label_path(label), method: :get do |f| %>
        <%= button_tag(type: :submit, class: "btn btn-outline-primary btn-sm ms-1") do %>
          <i class="bi bi-eye"></i> View
        <% end %>
      <% end %>
      <% if label.archived? %>
        <%= form_tag unarchive_label_path(label), method: :post  do |f| %>
          <%= button_tag(type: :submit, class: "btn btn-outline-success btn-sm ms-1") do %>
            <i class="bi bi-cart-check"></i> Unarchive
          <% end %>
        <% end %>
      <% else %>
        <%= form_tag archive_label_path(label), method: :post do |f| %>
          <%= button_tag(type: :submit, class: "btn btn-outline-danger btn-sm ms-1") do %>
            <i class="bi bi-archive"></i> Archive
          <% end %>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/labels/_labels.html.erb
<%#= content_tag(:div, "_labels.html.erb: #{labels.class.name}") %>
<table id="labels" class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col" class="text-center">Archived?</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <thead data-target="filter" class="d-none">
    <tr>
      <th scope="col"></th>
      <th data-type="label_name" scope="col">
        <!-- label_name search input box -->
      </th>
      <th data-type="archived" scope="col">
        <!-- archived search input box -->
      </th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody data-target="filter">
    <%= render partial: 'label', collection: labels.presenters, locals: { pager_params: pager_params } %>
  </tbody>
</table>

app/views/labels/edit.html.erb
<%= render "labels/form",
    postback_path: label_path,
    method: :patch,
    label: @label,
    header_text: "Edit Label",
    header_icon: "bi-bookmark",
    submit_button_text: "Save label",
    back_path: labels_path
%>

app/views/labels/index.html.erb
<%
add_a_label_button_text = "Add a label"
%>
<main class="form form-list-labels m-auto">
  <div data-controller="filter">
    <div class="h1 mb-3 fw-normal"><i class="bi bi-bookmark"></i> Labels</div>
    <%= render partial: "labels", object: @labels, locals: { pager_params: @pager_params } %>
  </div>
  <% unless @labels.any? %>
  <div>
    There are currently no labels.
    You can add one by clicking the
    <strong>
      <i class="bi bi-bookmark-check"></i> <%= add_a_label_button_text %>
    </strong>
    button below.
  </div>
  <% end %>
</main>

<%= render partial: "shared/pager", object: @pager_params %>

<div class="help-links">
  <%= link_to new_label_path, class: "btn btn-primary" do %>
    <i class="bi bi-bookmark-check"></i> <%= add_a_label_button_text %>
  <% end %>
</div>

app/views/labels/new.html.erb
<%= render "labels/form",
    postback_path: labels_path,
    label: @label,
    header_text: "New Label",
    header_icon: "bi-bookmark",
    submit_button_text: "Save label",
    back_path: labels_path
%>

app/views/labels/show.html.erb
<main class="form m-auto">
  <div class="h1 mb-3 fw-normal"><i class="bi bi-bookmark"></i>Label</div>
  <%= render partial: 'shared/label', object: @label.presenter %>

  <div class="help-links">
    <%= link_to "Back", labels_path %>
  </div>
</main>