config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stores do
    collection do
      get 'add'
      post 'add_create'
      get 'search'
    end
  end

  scope path: 'user' do
    resources :stores, controller: 'user_stores', as: 'user_stores' do
      # post 'archive', on: :member
      # post 'unarchive', on: :member

      collection do
        get 'add'
        post 'add'
      end
    end
  end
  post 'user/stores/link', to: 'user_stores#link', as: :link_user_store

  # Define routes for the Api::ZipCodesController
  namespace :api, defaults: { format: 'json' } do
    get 'zip_codes/zip_code_data/:zip_code', to: 'zip_codes#zip_code_data', as: :zip_code_data
  end

  resources :items, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  resources :shopping_lists

  scope path: 'user' do
    resources :shopping_lists, controller: 'user_shopping_lists', as: :user_shopping_lists do
      collection do
        get 'add'
        post 'add'
      end
    end
  end

  resources :labels, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  devise_for :users
end

app/models/label.rb
# frozen_string_literal: true

# The Label model for this application.
class Label < ApplicationRecord
  include ArchivableConcern
  include PagableConcern

  has_many :item_labels, dependent: :destroy
  has_many :items, through: :item_labels

  accepts_nested_attributes_for :item_labels

  validates :label_name, presence: true, uniqueness: { case_sensitive: false }

  attr_accessor :query

  def to_hash
    {
      id: id,
      label_name: label_name,
      items: sorted_items
    }
  end

  def to_json(*args)
    to_hash.to_json(*args)
  end

  private

  # TODO: Put this in a mixin.
  def sorted_items
    items.order(item_name: :asc).map do |item|
      {
        id: item.id,
        item_name: item.item_name,
        archived: item.archived
      }
    end
  end
end

app/views/shared/_debug.html.erb
<% if debug? %>
  <div class="container">
    <div class="row mb-3">
      <div class="col-md-2">
        @pager_params
      </div>
      <div class="col-md-10">
        <%= @pager_params.inspect %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-2">
        @resource.inspect
      </div>
      <div class="col-md-10">
        <%= @resource.inspect %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash_hash = flash.to_h.each_pair do |flash_type, value| %>
  <% if value.is_a?(Array) %>
    <%= render partial: "shared/flash_message",
               collection: value,
               locals: {
                  flash_type: flash_type
               }
    %>
  <% else %>
    <%= render partial: "shared/flash_message",
               locals: {
                  flash_type: flash_type,
                  flash_message: value
               }
    %>
  <% end %>
<% end %>

app/views/shared/_flash_message.html.erb
<div data-controller="flash"
      class="hot-alert alert d-none fade d-flex justify-content-between align-items-center"
      data-flash-target="container"
      data-flash-flash-json="<%= { flash_type => flash_message }.to_json %>"
>
  <!-- Icon -->
  <div>
    <i data-flash-target="icon" class="hot-alert-icon bi"></i>
  </div>

  <!-- Body (left-aligned) -->
  <div class="hot-alert-body flex-grow-1 text-left" data-flash-target="body"></div>

  <!-- Close button -->
  <div>
    <i data-flash-target="close" class="hot-alert-close-icon bi"></i>
  </div>
</div>

app/views/shared/_item.html.erb
<div class="mb-3">
  <h4 class="mb-1">Name</h4>
  <p><%= item.display_name %></p>
</div>

<div class="mb-3">
  <h4 class="mb-1">Archived?</h4>
  <p><%= item.display_archived_yes_no %></p>
</div>

app/views/shared/_item_search_results.html.erb
<% search_results.each_slice(2) do |slice| %>
  <div class="row">
    <% slice.each do |item| %>
      <div class="col">
        <%= check_box_tag 'item_ids[]',
                          item.id,
                          false,
                          id: "item_ids_#{item.id}",

              data: {
                action: "change->#{javascript_controller}#select",
                item_name: item.item_name
              }
        %>
        <%= item.item_name %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_label.html.erb
<div class="mb-3">
  <h4 class="mb-1">Name</h4>
  <p><%= label.display_name %></p>
</div>

<div class="mb-3">
  <h4 class="mb-1">Archived?</h4>
  <p><%= label.display_archived_yes_no %></p>
</div>

app/views/shared/_modal.html.erb
<%
data_controller_target = data_controller.underscore.camelize(:lower)
%>
<div data-controller="<%= data_controller %>"
      data-<%= data_controller %>-title="<%= text[:title] %>"
      data-<%= data_controller %>-body="<%= text[:body] %>"
      data-<%= data_controller %>-button-primary="<%= text[:primary_button] %>"
      data-<%= data_controller %>-button-secondary="<%= text[:secondary_button] %>"
      data-<%= data_controller %>-form-id="<%= form_id %>"
  >
  <%
  hidden.each do |key, value|
  %>
    <%= hidden_field_tag key, value %>
  <%
  end
  %>
  <div id="<%= modal_id %>" class="modal" tabindex="-1" data-<%= data_controller %>-target="modal">
    <div data-<%= data_controller %>-target="modalTarget"></div>
    <div data-<%= data_controller %>-target="<%= data_controller_target %>"></div>
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" data-<%= data_controller %>-target="modalTitle">
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" data-<%= data_controller %>-target="modalBody">
        </div>
        <div class="modal-footer" data-<%= data_controller %>-target="modalFooter">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" data-<%= data_controller %>-target="modalButtonSecondary">
          </button>
          <button type="button" class="btn btn-primary" data-<%= data_controller %>-target="modalButtonPrimary">
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav data-controller="nav-bar">
  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <i class="bi bi-egg-fried"></i>&nbsp;<%= render partial: "shared/site_name" %>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "Home", root_path, class: "nav-link px-2 text-secondary" %></li>
          <% if user_signed_in? %>
          <li><%= link_to "My Stores", user_stores_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "Shopping lists", user_shopping_lists_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "Items", items_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "Labels", labels_path, class: "nav-link px-2 text-white" %></li>

          <!-- li class="admin-menu-item"><%= link_to "Admin Shopping lists", shopping_lists_path, class: "nav-link px-2 text-white" %></li -->
          <% else %>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
          <% end %>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" id="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>
        <div class="text-end">
          <% if user_signed_in? %>
          <%= link_to "Logout",
                      destroy_user_session_path,
                      class: "btn btn-outline-light me-2",
                      data: {
                        turbo_method: :delete,
                        confirm: "Are you sure?",
                        turbo_confirm: "Are you sure?"
                      }
          %>
          <% active = false %>
          <%= link_to "Profile",
                      edit_user_registration_path,
                      class: ["btn btn-warning", active: active, disabled: active],
                      data: { action: "nav-bar#navigate" }
          %>
          <% else %>
          <% active = current_page?(new_user_session_path) %>
          <%= link_to "Login",
                      new_user_session_path,
                      class: ["btn btn-outline-light me-2", active: active, disabled: active],
                      data: { action: "nav-bar#navigate" }
          %>
          <% active = current_page?(new_user_registration_path) %>
          <%= link_to "Sign-up", new_user_registration_path,
                      class: ["btn btn-warning", active: active, disabled: active],
                      data: { action: "nav-bar#navigate" }
          %>
          <% end %>
        </div>
      </div>
    </div>
  </header>
</nav>

<%#= render partial: "shared/nav_bar_admin" %>

app/views/shared/_nav_bar_admin.html.erb
<nav class="admin-menu">
  <header class="p-3">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "Stores", user_stores_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "Items", items_path, class: "nav-link px-2 text-white" %></li>
          <li><a href="#" class="nav-link px-2 text-white">Labels</a></li>
        </ul>
        <div class="text-end">
        </div>
      </div>
    </div>
  </header>
</nav>

app/views/shared/_pager.html.erb
<% if pager.multiple_pages? %>
  <div data-controller="pager"
    data-pager-no-action-css-class="<%= pager.no_action_css %>"
  >
    <nav aria-label="Page navigation">
      <ul class="pagination pagination-lg" data-pager-target="pagerLinks">
        <li class="page-item <%= pager.previous_page_css %>">
          <%= link_to "Previous", pager.pager_href_for(page: pager.prev_page), class: "page-link" %>
        </li>
        <li class="page-item <%= pager.prev_page_jump_css %>">
          <%= link_to "...", pager.pager_href_for(page: pager.prev_page_jump), class: "page-link" %>
        </li>
        <% pager.pages_between_range.each do |page| %>
          <li class="page-item">
            <%= link_to page, pager.pager_href_for(page: page), class: "page-link #{pager.page_css(page)}" %>
          </li>
        <% end %>
        <li class="page-item <%= pager.next_page_jump_css %>">
          <%= link_to "...", pager.pager_href_for(page: pager.next_page_jump), class: "page-link" %>
        </li>
        <li class="page-item <%= pager.next_page_css %>">
          <%= link_to "Next", pager.pager_href_for(page: pager.next_page), class: "page-link" %>
        </li>
      </ul>
    </nav>
  </div>
<% end %>

app/views/shared/_site_name.html.erb
<%
container_css_class   ||= "site-name-container"
primary_css_class     ||= "food"
secondary_css_class   ||= "me"

mode = mode || :light
mode = mode.to_sym
mode = :light unless %i[light dark].include?(mode)
%>

<span class="<%= container_css_class %> <%= mode%>">
  <span class="<%= primary_css_class %> <%= mode%>">food</span><span class="<%= secondary_css_class %> <%= mode%>">Me</span>
</span>

app/views/shared/_store.html.erb
<div class="mb-3">
  <h4 class="mb-1">Name</h4>
  <p><%= store.store_name %></p>
</div>

<div class="mb-3">
  <h4 class="mb-1">Address</h4>
  <p><%= store.display_full_address %></p>
</div>

app/views/shared/_store_form.html.erb
<div data-controller="zip-code">
  <main class="form form-new-store">
    <%= simple_form_for(store, url: user_stores_path, wrapper: :horizontal_form) do |f| %>
      <div class="h1 mb-3 fw-normal"><%= header_text %></div>

      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :store_name,
                  label: "Name",
                  autofocus: true
      %>
      <%= f.input :address,
                  label: "Address"
      %>
      <%= f.input :address2,
                  label: "Address 2"
      %>
      <%= f.input :zip_code,
                  required: true,
                  input_html: {
                    data: {
                      "zip-code-target": "zipCode",
                      action: "blur->zip-code#fetchCityAndStateFromZipCode"
                    }
                  }
      %>
      <%= f.input :city,
                  input_html: {
                    data: {
                      "zip-code-target": "city"
                    }
                  }
      %>
      <%= f.association :state,
                        wrapper: :horizontal_form,
                        label_method: lambda { |state|
                          "#{state.state_name} (#{state.postal_abbreviation})"
                        },
                        prompt: "Select a state",
                        input_html: {
                          data: {
                            "zip-code-target": "state"
                          }
                        }
      %>

      <div class="form-actions">
        <%= f.button :submit,
                     class: "btn btn-primary",
                     data: {
                      "zip-code-target": "submitButton"
                     }
        %>

        <div class="help-links marginized">
          <%= link_to "Back", back_path %>
        </div>
      </div>
    <% end %>
  </main>
</div>