config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stores do
    collection do
      get 'add'
      post 'add_create'
      get 'search'
    end
  end

  scope path: 'user' do
    resources :stores, controller: 'user_stores', as: 'user_stores' do
      # post 'archive', on: :member
      # post 'unarchive', on: :member

      collection do
        get 'add'
        post 'add'
      end
    end
  end
  post 'user/stores/link', to: 'user_stores#link', as: :link_user_store

  # Define routes for the Api::ZipCodesController
  namespace :api, defaults: { format: 'json' } do
    get 'zip_codes/zip_code_data/:zip_code', to: 'zip_codes#zip_code_data', as: :zip_code_data
  end

  resources :items, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  resources :shopping_lists

  scope path: 'user' do
    resources :shopping_lists, controller: 'user_shopping_lists', as: :user_shopping_lists do
      collection do
        get 'add'
        post 'add'
      end
    end
  end

  resources :labels, except: %i[destroy] do
    post 'archive', on: :member
    post 'unarchive', on: :member
    get 'search', on: :collection
  end

  devise_for :users
end

app/models/item.rb
# frozen_string_literal: true

# The (store) Item model for this application.
class Item < ApplicationRecord
  include ArchivableConcern
  include PagableConcern

  has_many :user_shopping_list_items, dependent: :destroy

  has_many :item_labels, dependent: :destroy
  has_many :labels, through: :item_labels

  validates :item_name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/label.rb
# frozen_string_literal: true

# The Label model for this application.
class Label < ApplicationRecord
  include ArchivableConcern
  include PagableConcern

  has_many :item_labels, dependent: :destroy
  has_many :items, through: :item_labels

  accepts_nested_attributes_for :item_labels

  validates :label_name, presence: true, uniqueness: { case_sensitive: false }

  attr_accessor :query

  def to_hash
    {
      id: id,
      label_name: label_name,
      items: sorted_items
    }
  end

  def to_json(*args)
    to_hash.to_json(*args)
  end

  private

  # TODO: Put this in a mixin.
  def sorted_items
    items.order(item_name: :asc).map do |item|
      {
        id: item.id,
        item_name: item.item_name,
        archived: item.archived
      }
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# The controller for Items.
class ItemsController < ApplicationController
  include ItemSearchConcern

  before_action :authenticate_user!
  before_action :set_item, only: %i[show edit update archive unarchive]

  # GET /items or /items.json
  def index
    page = params[:page].to_i
    pager_params = Item.pager_params_for(page: page,
                                         pages_between: pager_pages_between,
                                         items_per_page: pager_items_per_page,
                                         pager_path: items_path)
    @pager_params = PagerPresenter.new(pager_params: pager_params, user: current_user, view_context: view_context)
    items = Item.page_for(page: page, order_by: :item_name, items_per_page: pager_items_per_page)
    @items = items.presenter(user: current_user, view_context: view_context)
  end

  # GET /items/1 or /items/1.json
  def show
    @item = PresenterDecorator.new(resource: @item, user: current_user, view_context: view_context)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { render :index, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /items/1 or /items/1.json
  def archive
    @item.archive!

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully archived.' }
      format.json { head :no_content }
    end
  end

  # POST /items/1 or /items/1.json
  def unarchive
    @item.unarchive!

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully unarchived.' }
      format.json { head :no_content }
    end
  end

  # GET /items/search
  def search
    locals = {
      search_results: @search_results,
      javascript_controller: 'shopping-list-items'
    }
    render partial: 'shared/item_search_results', locals: locals, layout: false
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:item_name, :archived)
  end
end

app/views/items/_form.html.erb
<main class="form form-user-store">
  <%= simple_form_for(item, id: "new-item") do |f| %>
    <div class="h1 mb-3 fw-normal">
      <i class="bi <%= header_icon %>"></i>
      <%= header_text %>
    </div>

    <% if f.object.errors[:base].present? %>
      <%= render partial: "shared/flash_message",
                  locals: {
                    flash_type: "alert",
                    flash_message: f.object.errors[:base].to_sentence
                  }
      %>
    <% end %>
    <div class="col-4">
      <%= f.input :item_name,
                  label: "Name",
                  autofocus: true,
                  input_html: {
                    autocomplete: "off"
                  }
      %>
      <%= f.input :archived,
                  label: "Archive"
      %>
    </div>
    <div class="form-actions">
      <%= f.button :submit,
                  submit_button_text,
                  class: "btn btn-primary"
      %>
      <div class="help-links marginized">
        <%= link_to "Back", back_path %>
      </div>
    </div>
  <% end %>
</main>

app/views/items/_item.html.erb
<%#= content_tag(:div, "_item.html.erb: item.class: #{item.class.name}, inspect: #{item.inspect}") %>
<tr id="<%= dom_id item %>" >
  <th scope="row"><%= pager_params.page_offset + item_counter + 1 %></th>
  <td><%= item.display_name %></td>
  <td class="text-center"><%= item.display_archived %></td>
  <td>
    <div class="fixed-width-buttons d-flex justify-content-center">
      <%= form_tag edit_item_path(item), method: :get do |f| %>
        <%= button_tag(type: :submit, class: "btn btn-outline-primary btn-sm ms-1") do %>
          <i class="bi bi-cart"></i> Edit
        <% end %>
      <% end %>
      <%= form_tag item_path(item), method: :get do |f| %>
        <%= button_tag(type: :submit, class: "btn btn-outline-primary btn-sm ms-1") do %>
          <i class="bi bi-eye"></i> View
        <% end %>
      <% end %>
      <% if item.archived? %>
        <%= form_tag unarchive_item_path(item), method: :post  do |f| %>
          <%= button_tag(type: :submit, class: "btn btn-outline-success btn-sm ms-1") do %>
            <i class="bi bi-cart-check"></i> Unarchive
          <% end %>
        <% end %>
      <% else %>
        <%= form_tag archive_item_path(item), method: :post do |f| %>
          <%= button_tag(type: :submit, class: "btn btn-outline-danger btn-sm ms-1") do %>
            <i class="bi bi-archive"></i> Archive
          <% end %>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/items/_items.html.erb
<%#= content_tag(:div, "_items.html.erb: #{items.class.name}") %>
<table id="items" class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col" class="text-center">Archived?</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <thead data-target="filter" class="d-none">
    <tr>
      <th scope="col"></th>
      <th data-type="item_name" scope="col">
        <!-- item_name search input box -->
      </th>
      <th data-type="archived" scope="col">
        <!-- archived search input box -->
      </th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody data-target="filter">
    <%= render partial: 'item', collection: items.presenters, locals: { pager_params: pager_params } %>
  </tbody>
</table>

app/views/items/_results.html.erb
<% items.each_slice(2) do |slice| %>
  <div class="row">
    <% slice.each do |item| %>
      <div class="col">
        <%= check_box_tag 'item_ids[]',
                          item.id,
                          @selected_item_ids&.include?(item.id),
                          id: "item_ids_#{item.id}",

              data: {
                action: "change->shopping-list-items#select",
                item_name: item.item_name
              }
        %>
        <%= item.item_name %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render "items/form",
    item: @item,
    header_text: "Edit Item",
    header_icon: "bi-cart",
    submit_button_text: "Save item",
    back_path: items_path
%>

app/views/items/index.html.erb
<%
add_an_item_button_text = "Add an item"
%>
<main class="form form-list-items m-auto">
  <div data-controller="filter">
    <div class="h1 mb-3 fw-normal"><i class="bi bi-cart"></i> Items</div>
    <%= render partial: "items", object: @items, locals: { pager_params: @pager_params } %>
  </div>
  <% unless @items.any? %>
  <div>
    There are currently no items.
    You can add one by clicking the
    <strong>
      <i class="bi bi-cart-check"></i> <%= add_an_item_button_text %>
    </strong>
    button below.
  </div>
  <% end %>
</main>

<%= render partial: "shared/pager", object: @pager_params %>

<div class="help-links">
  <%= link_to new_item_path, class: "btn btn-primary" do %>
    <i class="bi bi-cart-check"></i> <%= add_an_item_button_text %>
  <% end %>
</div>

app/views/items/new.html.erb
<%= render "items/form",
    item: @item,
    header_text: "New Item",
    header_icon: "bi-cart",
    submit_button_text: "Create item",
    back_path: items_path
%>

app/views/items/show.html.erb
<main class="form m-auto">
  <div class="h1 mb-3 fw-normal"><i class="bi bi-cart"></i>Item</div>
  <%= render partial: 'shared/item', object: @item.presenter %>

  <div class="help-links">
    <%= link_to "Back", items_path %>
  </div>
</main>